### ISSUE TITLE
The api key does not work on any of the starter kits for angular js

### ISSUE THREAD

**Issue by mlkingh** [Baasic/baasic-rest-api#3]
When the api key is changed in the theme folder app.config.json file nothing happens. the default them still shows.

**Comment by khorvat** [comment]
This issue was moved to Baasic/baasic-starterkit-angularjs-blog#1

**Comment by khorvat** [comment]
I have answered on your question here: https://github.com/Baasic/baasic-starterkit-angularjs-blog/issues/1
